import "./globals.css";
import type { Metadata } from "next";
import Image from "next/image";
import { Ubuntu } from "next/font/google";

import PageSelector from "./components/PageSelector";

import sidebar from "@/public/bg-sidebar-mobile.svg";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <header className="relative flex justify-center">
          <Image
            src={sidebar}
            alt=""
            className="min-w-full"
            placeholder="empty"
            priority={false}
          />
          <PageSelector />
        </header>
        <div className="relative">
          {children}
        </div>
        
      </body>
    </html>
  );
}
